ДЗ 1
Kukusikk/2020-1-Atom-QA-Python-A-Zadernovskaya pull request #1
Opened 2020-03-03 22:08 UTC by Kukusikk

# Домашнее задание №

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:
* написано по 5 параметризованных тестов для каждой из структур данных 
* в качестве редактора кода был использован autopep8
*

2020-03-05 21:39 UTC, sniiick requested changes
1. *.pyc файлы в ревью
2. Еще раз прогнать линтер и проверить стилистику всего проекта
3. Можно упростить конструкции

2020-03-05 21:39 UTC, snicks92 commented on .gitignore
> +.idea
Не хватает пустой строки в конце файла

2020-03-05 21:39 UTC, snicks92 commented on mytest/test_Dictionary.py
> +    # @pytest.mark.parametrize(
Лишние комменты

2020-03-05 21:39 UTC, snicks92 commented on mytest/test_Dictionary.py
> +        pass
pass не нужен

2020-03-05 21:39 UTC, snicks92 commented on mytest/test_Int.py
> +    def test_is(self, x=some_data, y=some_data):
x и y будут равны объекту функции some_data, а не результату фикстуры

2020-03-05 21:39 UTC, snicks92 commented on mytest/test_Int.py
> +        return a
просто `return 7`

2020-03-05 21:39 UTC, snicks92 commented on mytest/test_Int.py
> +        assert (x is y) == True
просто `assert x is y`

2020-03-05 21:39 UTC, snicks92 commented on mytest/test_List.py
> +class TestForList:
2 строки отступа от импорта

2020-03-05 21:39 UTC, snicks92 commented on mytest/test_List.py
> +        assert x==y
Пробелы вокруг ==

2020-03-05 21:39 UTC, snicks92 commented on mytest/test_List.py
> +    @pytest.mark.parametrize("x,y", [([],[]), ([9,9,6,7],[7,6,9,9])])
отступы между функциями

2020-03-08 14:39 UTC, Kukusikk commented
Прошу @snicks92 или @z1ll1 проверить изменения.

Что было исправлено:
* В .gitignore добавлены файлы, также эти файлы были удалены из отслеживаемых git
* Удалены лишении комментарии, добавлены где надо пробелы/перенос строки(частично с помощью autopep8, частично руками)
* Изменены некоторые конструкции в целях упрощения ( убран везде pass, изменен метод test_is в файле mytest/test_Int.py, конструкции типа (x is y) == True ---> в x is y

2020-03-08 15:39 UTC, sniiick approved these changes
Вот теперь хорошо

2020-03-08 15:39 UTC, merged